client/src/components/createPostP/BodyInput.tsx
client/src/components/createPostP/TagInput.tsx
client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/ProfilePreview.tsx
client/src/components/postDetailP/RecommendedPost.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/ReplyInput.tsx
client/src/pages/PostDetail.tsx
client/src/sagas/post/postSaga.ts
client/src/sagas/post/postSagaActions.ts

[FE][FIX] CreatePost 에디터 및 태그 버그 수정

---

client/src/GloablStyles.tsx
client/src/components/createPostP/BodyInput.tsx
client/src/components/createPostP/TagInput.tsx
client/src/components/createPostP/TitleInput.tsx
client/src/pages/CreatePost.tsx
client/src/slices/postInputSlice.tsx
client/src/slices/validationSlice.tsx
client/src/store/store.tsx

[FE][FEAT] 게시글 생성 기능 구현

---

client/src/components/updatePostP/BodyInput.tsx
client/src/components/updatePostP/TagInput.tsx
client/src/components/updatePostP/TitleInput.tsx
client/src/pages/UpdatePost.tsx

[FE][FEAT] 게시물 수정 기능 구현

---

client/package.json
client/src/api/api.ts
client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/ReplyInput.tsx
client/src/mocks/handlers.ts
client/src/pages/CreatePost.tsx
client/src/pages/PostDetail.tsx
client/src/slices/commentSlice.tsx
client/src/slices/postSlice.tsx
client/src/slices/replySlice.tsx
client/src/types/PostDetail.d.ts

[FE][FEAT] 댓글, 답글 CRUD 구현

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/DropdownButton.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/ReplyInput.tsx
client/src/mocks/postData.ts
client/src/pages/PostDetail.tsx
client/src/slices/replySlice.tsx
client/src/types/PostDetail.d.ts

[FE][FIX] 게시물 답글 수정 버그 해결

---

client/src/api/postApi.ts
client/src/api/replyApi.ts
client/src/components/createPostP/BodyInput.tsx
client/src/components/createPostP/TagInput.tsx
client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/updatePostP/BodyInput.tsx
client/src/components/updatePostP/TagInput.tsx
client/src/components/updatePostP/TitleInput.tsx
client/src/mocks/handlers.ts
client/src/pages/CreatePost.tsx
client/src/pages/PostDetail.tsx
client/src/pages/UpdatePost.tsx
client/src/slices/commentSlice.tsx
client/src/slices/postSlice.tsx
client/src/slices/replySlice.tsx
client/src/types/PostDetail.d.ts

[FE][FEAT] 게시글 추가 기능 및 소개 페이지 명함 기능 구현

---

client/src/pages/PostDetail.tsx

[FE][FIX] 게시글 상세 페이지 데이터 형태 수정

---

client/src/api/commentApi.ts
client/src/api/postApi.ts
client/src/api/replyApi.ts
client/src/pages/PostDetail.tsx

[FE][FIX] 게시글 상세 페이지 데이터 형태 및 API 수정

---

client/src/api/commentApi.ts
client/src/components/postDetailP/Comment.tsx
client/src/pages/PostDetail.tsx
client/src/pages/UpdatePost.tsx
client/src/slices/commentSlice.tsx
client/src/types/PostDetail.d.ts

[FE][FIX] 댓글 페이지 지정 및 댓글 API 수정

---

client/src/api/commentApi.ts
client/src/api/replyApi.ts
client/src/components/postDetailP/Reply.tsx
client/src/slices/replySlice.tsx
client/src/types/PostDetail.d.ts

[FE][FIX] 답글 페이지 지정 및 댓글 API 수정

---

client/src/api/commentApi.ts
client/src/api/replyApi.ts
client/src/pages/PostDetail.tsx

[FE][FIX] 댓글, 답글 API 수정

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/Reply.tsx

[FE][FIX] 댓글, 답글 필드명 수정

---

client/src/components/postDetailP/Reply.tsx
client/src/components/updatePostP/TitleInput.tsx

[FE][FIX] 답글 page 변수 수정

---

client/src/components/postDetailP/Reply.tsx
client/src/components/updatePostP/BodyInput.tsx
client/src/pages/PostDetail.tsx

[FE][FIX] 게시글 수정 본문 코드 오류 수정

---

client/src/components/updatePostP/BodyInput.tsx
client/src/pages/PostDetail.tsx

[FE][FIX] 게시글 상세 모달창 테스트

---

client/src/components/updatePostP/BodyInput.tsx

[FE][FIX] 게시글 수정 버그 해결

---

client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/Reply.tsx

[FE][FIX] 댓글, 답글 버그 수정

---

client/src/pages/PostDetail.tsx

[FE][FEAT] 게시글 좋아요, 싫어요 버그 수정

---

client/src/api/postApi.ts
client/src/components/postDetailP/Comment.tsx
client/src/pages/PostDetail.tsx

게시글, 답글 좋아요, 싫어요 버그 수정 및 북마크 기능 추가

[FE][FEAT] 게시글, 답글 좋아요, 싫어요 버그 수정 및 북마크 기능 추가

---

client/src/components/createPostP/BodyInput.tsx
client/src/pages/PostDetail.tsx

게시글 좋아요, 싫어요 버그 수정 및 이미지 업로드 테스트

[FE][FEAT] 게시글 좋아요, 싫어요 버그 수정 및 이미지 업로드 테스트

---

client/src/components/postDetailP/Comment.tsx
client/src/pages/CreatePost.tsx
client/src/pages/PostDetail.tsx

[FE][FIX] 게시글 좋아요, 싫어요 버그 수정

---

server/src/main/java/com/teamdragon/dragonmoney/app/domain/category/service/CategoryService.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/comment/dto/CommentDto.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/comment/entity/Comment.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/comment/service/CommentService.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/image/mapper/ImageMapper.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/image/service/ImageService.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/posts/dto/PostsDto.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/posts/entity/Posts.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/posts/mapper/PostsMapper.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/posts/service/PostsService.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/reply/dto/ReplyDto.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/reply/entity/Reply.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/reply/service/ReplyService.java
server/src/main/java/com/teamdragon/dragonmoney/app/domain/tag/dto/TagDto.java

- 게시글 삭제 권한 문제 수정 
- 글 수정 여부 문제 수정 
- 댓글 수정, 삭제 권한 실패 문제 수정 
- 답글 수정, 삭제 권한 실패 문제 수정 
- 엔티티 좋아요, 싫어요 반영 문제 수정

[BE][FIX]: 로직 이슈 처리

---

client/src/api/commentApi.ts
client/src/api/postApi.ts
client/src/api/replyApi.ts
client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/ReplyInput.tsx

[FE][FIX] 댓글 버그 수정

---

client/src/api/commentApi.ts
client/src/api/replyApi.ts
client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/RecommendedPost.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/ReplyInput.tsx
client/src/pages/CreatePost.tsx
client/src/pages/PostDetail.tsx
client/src/slices/replySlice.tsx
client/src/types/PostDetail.d.ts

[FE][FIX] 게시글 상세페이지 기능 수정 및 버그 해결

---

client/src/pages/CreatePost.tsx

[FE][FIX] 게시물 생성 후 화면 이동 처리

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/Reply.tsx
client/src/pages/PostDetail.tsx
client/src/slices/postSlice.tsx
client/src/types/PostDetail.d.ts

[FE][FIX] 소개 페이지 명함 유저 소개 데이터 패칭

---

client/src/api/postApi.ts
client/src/components/postDetailP/Comment.tsx

[FE][FIX] 싫어요 버그 수정

---

client/src/pages/PostDetail.tsx
client/src/store/store.tsx

[FE][FIX] 신고, 삭제, 소개창 버그 수정

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/ReplyInput.tsx
client/src/pages/PostDetail.tsx
client/src/types/PostDetail.d.ts

[FE][FIX] 게시글 상세페이지 스타일 수정

---

client/src/api/apiSlice.ts
client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/ReplyInput.tsx
client/src/pages/PostDetail.tsx

[FE][FIX] 게시물 상세 페이지 스타일 수정

---

client/src/components/common/HeaderNav.tsx

[FE][FIX] Nav 항목 클릭 시 스크롤 이동

---

client/src/components/postDetailP/Comment.tsx

[FE][FIX] 답글 열기 버튼 스타일 수정

---

.github/workflows/npm.yml
client/src/components/postDetailP/DropdownButton.tsx
client/src/components/postDetailP/RecommendedPost.tsx
client/src/pages/PostDetail.tsx

[FE][FIX] 배포 자동화 환경변수 추가 

---

client/src/pages/PostDetail.tsx

[FE][FIX] 모달창 배경 이슈 해결

---

client/src/GloablStyles.tsx
client/src/components/postDetailP/RecommendedPost.tsx
client/src/components/postDetailP/ReplyInput.tsx
client/src/components/updatePostP/TitleInput.tsx
client/src/pages/PostDetail.tsx
client/src/pages/UpdatePost.tsx

[FE][FIX] 신고하기 에러 수정 및 스타일 변경

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/updatePostP/TagInput.tsx
client/src/pages/CreatePost.tsx
client/src/pages/PostDetail.tsx

1. 삭제한 댓글, 답글 좋아요 싫어요 비활성화
2. 신고 이미지 클릭 버그 해결
3. 코드 스타일 수정

[FE][FIX] 신고 이미지 클릭 버그 해결

---

client/src/pages/PostDetail.tsx

[FE][FIX] 신고 유효성 검사 수정

---

client/src/components/createPostP/TagInput.tsx
client/src/components/createPostP/TitleInput.tsx
client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/ReplyInput.tsx
client/src/components/updatePostP/BodyInput.tsx
client/src/components/updatePostP/TagInput.tsx
client/src/components/updatePostP/TitleInput.tsx
client/src/pages/PostDetail.tsx

게시물 생성, 수정,  상세 페이지 Input 태그 스타일 수정

[FE][FIX] 게시물 생성, 수정,  상세 페이지 Input 태그 스타일 수정

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/Tag.tsx
client/src/components/updatePostP/TagInput.tsx
client/src/pages/PostDetail.tsx

게시물 상세 페이지 태그 추가 및 좋아요 싫어요 스타일 수정

[FE][FIX] 게시물 상세 페이지 태그 추가 및 좋아요 싫어요 스타일 수정

---

client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/ReplyInput.tsx

[FE][FEAT] 신고된 댓글에 답급 추가 불가 

---

client/src/components/postDetailP/Reply.tsx

[FE][FIX] 답글 오탈자 수정

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/Reply.tsx

[FE][FIX] 신고된 댓글, 답글 스타일 지정

---

client/src/types/PostDetail.d.ts

[FE][CHORE] 타입 정보 변경

---

client/src/pages/PostDetail.tsx

[FE][FIX] 게시물 상세 페이지 렌더링 문제 해결

---

client/package-lock.json
client/package.json
client/src/components/common/Loading.tsx
client/src/components/common/Tag.tsx
client/src/components/createPostP/BodyInput.tsx
client/src/components/myPageP/DropdownButton.tsx
client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/DropdownButton.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/updatePostP/BodyInput.tsx
client/src/components/updatePostP/TagInput.tsx
client/src/components/updatePostP/TitleInput.tsx
client/src/index.tsx
client/src/pages/PostDetail.tsx
client/src/pages/UpdatePost.tsx
client/src/slices/postInputSlice.tsx
client/src/slices/postSlice.tsx
client/src/types/PostDetail.d.ts

[FE][FIX] 게시물 내용 변경 시에만 수정 가능하도록 수정

---

client/src/components/common/PostBtn.tsx
client/src/pages/CreatePost.tsx
client/src/pages/Main.tsx
client/src/pages/PostDetail.tsx
client/src/pages/UpdatePost.tsx

[FE][FIX] 게시물 작성 페이지 리로딩 문제 해결 등

---

client/src/pages/CreatePost.tsx

[FE][FIX] 게시물 작성 페이지 리로딩 문제 해결

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/Reply.tsx
client/src/pages/PostDetail.tsx

[FE][FIX] 좋아요, 싫어요, 북마크 throttling 처리

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/Reply.tsx
client/src/pages/PostDetail.tsx

[FE][FIX] 명함 소개 내용 버그 해결

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/RecommendedPost.tsx
client/src/components/postDetailP/Reply.tsx
client/src/pages/PostDetail.tsx
client/src/types/PostDetail.d.ts

1. 추천 게시물 스타일 수정 
2. 좋아요, 싫어요 Debounce 처리

[FE][FIX] 추천 게시물 스타일 수정 등

---

client/src/App.tsx
client/src/components/common/Loading.tsx
client/src/pages/CreatePost.tsx
client/src/pages/PostDetail.tsx

[FE][FIX] Header, Footer 지연로딩 해소

---

client/src/components/common/Loading.tsx
client/src/components/postDetailP/Comment.tsx
client/src/pages/PostDetail.tsx

[FE][FIX] Header, Footer 렌더링 최적화

---

client/src/components/createPostP/TitleInput.tsx
client/src/components/updatePostP/TitleInput.tsx

[FE][FIX] 게시물 제목 유효성 검사 수정

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/ReplyInput.tsx

[FE][FEAT] 댓글, 답글 줄 바꾸기 기능 구현 및 스타일 수정

---

client/src/components/postDetailP/CommentInput.tsx

[FE][FEAT] 댓글, 답글 줄 바꾸기 버그 해결

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/Reply.tsx

[FE][FEAT] 댓글, 답글 수정 시 줄바꾸기 구현

---

client/src/components/postDetailP/ReplyInput.tsx

[FE][FEAT] 답글 스타일 수정

---

client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/ReplyInput.tsx

[FE][FEAT] 답글 댓글 버그 수정

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/RecommendedPost.tsx
client/src/components/postDetailP/Reply.tsx

[FE][FEAT] 답글 댓글 수정 시 textarea 데이터 패칭 구현

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/slices/commentSlice.tsx
client/src/types/PostDetail.d.ts

[FE][FIX] 댓글 추가 시 인덱스 문제 해결

---

client/src/components/createPostP/BodyInput.tsx
client/src/components/createPostP/TagInput.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/DropdownButton.tsx
client/src/components/postDetailP/ProfilePreview.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/ReplyInput.tsx
client/src/components/postDetailP/Tag.tsx
client/src/pages/Main.tsx
client/src/pages/PostDetail.tsx

[FE][FIX] 메인 페이지 데이터 패칭 버그 수정

---

client/src/api/commentApi.ts
client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentDropdownButton.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/PostDropdownButton.tsx
client/src/pages/PostDetail.tsx
client/src/slices/commentSlice.tsx
client/src/types/PostDetail.d.ts

[FE][FEAT] 댓글 필터링 기능 추가 

---

client/src/components/createPostP/BodyInput.tsx
client/src/components/createPostP/TagInput.tsx
client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentDropdownButton.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/PostDropdownButton.tsx
client/src/components/postDetailP/RecommendedPost.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/ReplyInput.tsx
client/src/components/updatePostP/BodyInput.tsx
client/src/components/updatePostP/TagInput.tsx
client/src/components/updatePostP/TitleInput.tsx
client/src/pages/PostDetail.tsx
client/src/slices/commentSlice.tsx
client/src/slices/postInputSlice.tsx
client/src/slices/postSlice.tsx
client/src/slices/replySlice.tsx
client/src/types/PostDetail.d.ts

1. 댓글 필터링으로 인한 답글 패칭 버그 해결
2. 불필요한 코드 제거 및 코드 스타일 변경

[FE][FIX] 댓글 필터링으로 인한 답글 패칭 버그 해결 등

---

client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/CommentInput.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/postDetailP/ReplyInput.tsx
client/src/pages/PostDetail.tsx

로그인되지 않은 사용자 로그인 페이지로 리다이렉트 구현

[FE][FEAT] 로그인되지 않은 사용자 로그인 페이지로 리다이렉트 구현

---

client/src/components/postDetailP/CommentDropdownButton.tsx
client/src/pages/PostDetail.tsx

[FE][FEAT] 신고하기 유효성 검사 항목 추가

---

client/src/components/common/PostBtn.tsx
client/src/components/postDetailP/CommentDropdownButton.tsx
client/src/pages/CreatePost.tsx
client/src/pages/PostDetail.tsx
client/src/pages/UpdatePost.tsx

신고 유효성 검사 및 로그인 하지 않은 유저 리다이렉트 경로 지정

[FE][FIX] 신고 유효성 검사 및 로그인 하지 않은 유저 리다이렉트 경로 지정

---

client/src/api/postApi.ts
client/src/pages/CreatePost.tsx
client/src/pages/UpdatePost.tsx

[FE][FIX] 이미제 삭제 로직 수정

---

client/src/components/createPostP/BodyInput.tsx
client/src/components/createPostP/TagInput.tsx
client/src/components/createPostP/TitleInput.tsx
client/src/components/postDetailP/Comment.tsx
client/src/components/postDetailP/Reply.tsx
client/src/components/updatePostP/BodyInput.tsx
client/src/components/updatePostP/TagInput.tsx
client/src/components/updatePostP/TitleInput.tsx
client/src/pages/CreatePost.tsx
client/src/pages/PostDetail.tsx
client/src/pages/UpdatePost.tsx

[FE][FEAT] 게시물 생성, 수정 페이지 반응현 구현 등
